executor:
  name: python
  options:
    entry: __init__.py
inputs_def:
  - handle: text
    description: "The text content to encode into the QR code (URL, message, contact
      info, etc.)"
    json_schema:
      type: string
    nullable: false
  - handle: picture
    description: "Optional background image file to embed behind the QR code for branding"
    json_schema:
      type: string
      ui:widget: file
    value:
    nullable: true
  - handle: colorized
    description: "Enable colorization to create colored QR codes instead of black and white"
    json_schema:
      type: boolean
    value: false
  - handle: contrast
    description: "Adjust the visual contrast of the QR code (higher values = more contrast)"
    json_schema:
      type: number
      minimum: 0.1
      ui:options:
        step: 0.1
    value: 1
  - handle: brightness
    description: "Control the brightness level of the generated QR code"
    json_schema:
      type: number
      minimum: 0.1
      ui:options:
        step: 0.1
    value: 1
  - handle: level
    description: "Error correction level: L=Low(~7%), M=Medium(~15%),
      Q=Quartile(~25%), H=High(~30%)"
    json_schema:
      enum:
        - L
        - M
        - Q
        - H
      ui:options:
        labels:
          - "Low (7%)"
          - "Medium (15%)"
          - "Quartile (25%)"
          - "High (30%)"
    value: M
  - handle: version
    description: "QR code version (size): 1=21x21 modules, higher numbers = larger
      size and capacity"
    json_schema:
      type: number
      ui:options:
        step: 1
      minimum: 1
    value: 1
outputs_def:
  - handle: output
    description: "File path of the generated QR code image"
    json_schema:
      type: string
description: "Generates customizable QR codes with advanced styling options.
  Accepts text content, optional background images, and various visual settings
  including contrast, brightness, colorization, and error correction levels.
  Outputs the generated QR code image file path and displays a visual preview."
title: Generator QR Code
