executor:
  name: python
  options:
    entry: __init__.py
inputs_def:
  - handle: text
    json_schema:
      type: string
    value: ""
    nullable: false
  - handle: picture
    json_schema:
      type: string
      ui:widget: file
    value:
    nullable: true
  - handle: colorized
    json_schema:
      type: boolean
    value: false
  - handle: contrast
    json_schema:
      type: number
      minimum: 0.1
      ui:options:
        step: 0.1
    value: 1
  - handle: brightness
    json_schema:
      type: number
      minimum: 0.1
      ui:options:
        step: 0.1
    value: 1
  - handle: level
    json_schema:
      enum:
        - L
        - M
        - Q
        - H
      ui:options:
        labels:
          - ""
          - ""
          - ""
          - ""
    value: M
  - handle: version
    json_schema:
      type: number
      ui:options:
        step: 1
      minimum: 1
    value: 1
outputs_def:
  - handle: output
    json_schema:
      type: string
description: "Generates customizable QR codes with advanced styling options.
  Accepts text content, optional background images, and various visual settings
  including contrast, brightness, colorization, and error correction levels.
  Outputs the generated QR code image file path and displays a visual preview."
title: Generator QR Code
