executor:
  name: nodejs
  options:
    entry: main.ts
inputs_def:
  - handle: input
    description: "QR code image input in various formats: Base64 text, Base64
      string, file path, or binary data"
    json_schema:
      anyOf:
        - type: string
          ui:widget: text
        - type: string
        - type: string
          ui:widget: file
        - contentMediaType: oomol/bin
      ui:options:
        labels:
          - Base64 with Text
          - Base64 with String
          - FilePath
          - ArrayBuffer
outputs_def:
  - handle: output
    description: "Decoded text content extracted from the QR code"
    json_schema:
      type: string
ui:
  default_width: 538.1221733443234
title: Reader QR Code
description: "Reads and decodes QR codes from various input formats including
  Base64 text/string, file paths, and binary data. Extracts the text content
  encoded within QR code images and returns it as a string output."
