executor:
  name: nodejs
  options:
    entry: main.ts
inputs_def:
  - handle: input
    description: "Image input to check for QR code presence: Base64 text, Base64
      string, file path, or binary data"
    json_schema:
      anyOf:
        - type: string
          ui:widget: text
        - type: string
        - type: string
          ui:widget: file
        - contentMediaType: oomol/bin
      ui:options:
        labels:
          - Base64 with Text
          - Base64 with String
          - FilePath
          - ArrayBuffer
outputs_def:
  - handle: output
    description: "Boolean result: true if QR code is detected, false if no QR code is found"
    json_schema:
      type: boolean
title: Exist QR Code
description: "Checks whether an image contains a QR code. Accepts various input
  formats including Base64 text/string, file paths, and binary data. Analyzes
  the provided image and returns a boolean value indicating the presence of a QR
  code."
